stages:
    - debug
    - release
    - deliver
    - trigger

debug:
    stage: debug
    script:
        - ./build debug
    except:
         - master

release:
    stage: release
    script:
        - ./build release
    except:
        - master

delivery:
    stage: deliver
    variables:
        MIU_PATH: "/opt/staging/miu"
        INC_PATH: "$MIU_PATH/include"
        DBG_PATH: "$MIU_PATH/lib-dbg"
        REL_PATH: "$MIU_PATH/lib-rel"
        BIN_PATH: "$MIU_PATH/binaries"
        UT_PATH: "$MIU_PATH/unittest"
    script:
        - ./build debug
        - ./build release

          #- mkdir -p $INC_PATH
          #- rm -fr $INC_PATH/com
          #- cp -frv ./include/com $INC_PATH

          #- mkdir -p $DBG_PATH
          #- cp -fv debug/libcom.a $DBG_PATH

          #- mkdir -p $REL_PATH
          #- cp -fv release/libcom.a $REL_PATH

          #- mkdir -p $UT_PATH
          #- cp -fv release/ut_com $UT_PATH

    only:
        - master

downstream-project:
    stage: trigger
    script:
        - echo "curl -X POST -F token=<downstream-project-token> -F ref=master <url>/api/v4/projects/<downstream-project-id>/trigger/pipeline"
    only:
        - master
