#!/usr/bin/bash

PROJECT_NAME=testmkt
BUILD_VERBOSE=OFF
source $TOOLCHAIN_PATH/build.in

if [[ $1 == "command" ]]; then
    echo "testmkt specific command"

else
     echo "ERROR: unknown command"
fi
